#!/usr/bin/env python3
"""Measure a factory run: tokens per seat, time per stage, verdicts.

Reads three sources that exist after any run, so every number in FACTORY.md section 7 can be
regenerated by anyone with the same files:

- the seats' Claude Code transcripts (one JSONL per session, tagged with the seat's name);
- the result repository's git history (commit times and authors per stage folder);
- the room export `room.json` from BAND (dispatch time, ACCEPT and REJECT verdicts).

Usage:
  tools/factory_numbers.py --transcripts ~/.claude/projects/<workspace-dir> \
      --repo <result-repo> --since 2026-10-04T09:00:00+03:00 [--room room.json] [--prices prices.json]

prices.json maps a model id to USD per million tokens, e.g.
  {"claude-sonnet-5-5": {"input": 0, "output": 0, "cache_write": 0, "cache_read": 0}}
Without it the cost column is left empty rather than guessed.
"""
import argparse
import collections
import datetime as dt
import json
import pathlib
import re
import subprocess

SEATS = ["coordinator", "implementer", "reviewer", "spec-auditor", "customer"]
FIELDS = {"input_tokens": "input", "output_tokens": "output",
          "cache_creation_input_tokens": "cache_write", "cache_read_input_tokens": "cache_read"}


def parse_ts(s):
    return dt.datetime.fromisoformat(s.replace("Z", "+00:00"))


def seat_of(path):
    """Seat name from the transcript's agent-name record, if it is one of ours."""
    with open(path) as f:
        for _, line in zip(range(20), f):
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            if rec.get("type") == "agent-name":
                return rec.get("agentName")
    return None


def tokens(transcripts, since, until):
    per_seat = {s: collections.Counter() for s in SEATS}
    models = {s: set() for s in SEATS}
    for path in pathlib.Path(transcripts).glob("*.jsonl"):
        seat = seat_of(path)
        if seat not in per_seat:
            continue
        seen = set()
        for line in open(path):
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            msg, ts = rec.get("message"), rec.get("timestamp")
            if not isinstance(msg, dict) or not msg.get("usage") or not ts:
                continue
            t = parse_ts(ts)
            if t < since or (until and t > until) or msg.get("id") in seen:
                continue
            seen.add(msg.get("id"))
            models[seat].add(msg.get("model"))
            for k, name in FIELDS.items():
                per_seat[seat][(msg.get("model"), name)] += msg["usage"].get(k) or 0
    return per_seat, models


def stage_times(repo, since):
    log = subprocess.run(["git", "-C", repo, "log", "--reverse", f"--since={since.isoformat()}",
                          "--format=%H%x09%aI%x09%an", "--name-only"],
                         capture_output=True, text=True, check=True).stdout
    stages, authors = {}, collections.Counter()
    commit = None
    for line in log.splitlines():
        if "\t" in line:
            sha, when, author = line.split("\t")
            commit = (sha, parse_ts(when), author)
            authors[author] += 1
        elif line and commit:
            m = re.match(r"stage-(\d+)/", line)
            if m:
                first, last = stages.get(int(m.group(1)), (commit[1], commit[1]))
                stages[int(m.group(1))] = (min(first, commit[1]), max(last, commit[1]))
    return stages, authors


def verdicts(room_path):
    room = json.load(open(room_path))
    msgs = sorted(room.get("messages", []), key=lambda m: m.get("insertedAt", ""))
    dispatch = next((m for m in msgs if m.get("senderType") == "User" and len(m.get("content", "")) > 100), None)
    counts = collections.Counter()
    log = []
    for m in msgs:
        # A verdict is a message whose first word, after any @mentions, is ACCEPT or REJECT.
        body = re.sub(r"^(\s*(@\[\[[^\]]*\]\]|@[\w-]+)[\s,:]*)+", "", m.get("content") or "")
        word = re.match(r"\W*(ACCEPT|REJECT)\b", body.strip().upper())
        if word:
            counts[(m.get("senderName"), word.group(1))] += 1
            rev = re.search(r"\b[0-9a-f]{7,40}\b", body)
            log.append((m.get("insertedAt", ""), m.get("senderName"), word.group(1),
                        rev.group(0)[:10] if rev else "", m.get("id", "")))
    humans = sum(1 for m in msgs if m.get("senderType") == "User" and m.get("messageType") != "event")
    return dispatch, counts, humans, log


def cost(counter, prices):
    if not prices:
        return None
    total = 0.0
    for (model, field), n in counter.items():
        p = prices.get(model)
        if p is None:
            return None
        total += n * p[field] / 1_000_000
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--transcripts", required=True)
    ap.add_argument("--repo", required=True)
    ap.add_argument("--since", required=True, help="dispatch time, ISO 8601 with offset")
    ap.add_argument("--until")
    ap.add_argument("--room")
    ap.add_argument("--prices")
    a = ap.parse_args()
    since = parse_ts(a.since)
    until = parse_ts(a.until) if a.until else None
    prices = json.load(open(a.prices)) if a.prices else None

    per_seat, models = tokens(a.transcripts, since, until)
    print("### Model spend\n")
    print("| Seat | Model | Input | Output | Cache write | Cache read | Cost (USD, list) |")
    print("|---|---|---|---|---|---|---|")
    grand = collections.Counter()
    for seat in SEATS:
        c = per_seat[seat]
        grand.update(c)
        sums = collections.Counter()
        for (_, field), n in c.items():
            sums[field] += n
        usd = cost(c, prices)
        print(f"| {seat} | {', '.join(sorted(m for m in models[seat] if m)) or '-'} | {sums['input']:,} | "
              f"{sums['output']:,} | {sums['cache_write']:,} | {sums['cache_read']:,} | "
              f"{'' if usd is None else f'{usd:,.2f}'} |")
    gs = collections.Counter()
    for (_, field), n in grand.items():
        gs[field] += n
    usd = cost(grand, prices)
    print(f"| **Total** | | {gs['input']:,} | {gs['output']:,} | {gs['cache_write']:,} | {gs['cache_read']:,} | "
          f"{'' if usd is None else f'{usd:,.2f}'} |\n")

    stages, authors = stage_times(a.repo, since)
    print("### Time\n")
    print("| Stage | First commit | Last commit | Span |")
    print("|---|---|---|---|")
    for n in sorted(stages):
        first, last = stages[n]
        print(f"| {n} | {first:%H:%M} | {last:%H:%M} | {last - first} |")
    print(f"\nCommits by author since dispatch: " + ", ".join(f"{k} {v}" for k, v in authors.most_common()) + "\n")

    if a.room:
        dispatch, counts, humans, log = verdicts(a.room)
        if dispatch:
            print(f"Dispatch: {dispatch['insertedAt']} (human messages in the room: {humans})\n")
        print("| Seat | ACCEPT | REJECT |")
        print("|---|---|---|")
        for seat in SEATS:
            print(f"| {seat} | {counts[(seat, 'ACCEPT')]} | {counts[(seat, 'REJECT')]} |")
        print("\n### Verdict log (cite these room.json message ids in FACTORY.md)\n")
        print("| Time (UTC) | Seat | Verdict | Revision | room.json message id |")
        print("|---|---|---|---|---|")
        for when, seat, verdict, rev, mid in log:
            print(f"| {when[:19].replace('T', ' ')} | {seat} | {verdict} | `{rev}` | `{mid}` |")


if __name__ == "__main__":
    main()
